let employees = [{ "id": 1, "first_name": "Leese", "last_name": "Tansill", "email": "ltansill0@guardian.co.uk", "gender": "Female" },
{ "id": 2, "first_name": "Towney", "last_name": "Gerrey", "email": "tgerrey1@facebook.com", "gender": "Male" },
{ "id": 3, "first_name": "Selene", "last_name": "Disbrow", "email": "sdisbrow2@nytimes.com", "gender": "Female" },
{ "id": 4, "first_name": "Gordon", "last_name": "Sabbins", "email": "gsabbins3@dailymotion.com", "gender": "Male" },
{ "id": 5, "first_name": "Gayel", "last_name": "Wait", "email": "gwait4@canalblog.com", "gender": "Female" },
{ "id": 6, "first_name": "Juliana", "last_name": "Wandrey", "email": "jwandrey5@ft.com", "gender": "Polygender" },
{ "id": 7, "first_name": "Griselda", "last_name": "Langland", "email": "glangland6@simplemachines.org", "gender": "Female" },
{ "id": 8, "first_name": "Antonino", "last_name": "Mailey", "email": "amailey7@illinois.edu", "gender": "Male" },
{ "id": 9, "first_name": "Beverie", "last_name": "Crankshaw", "email": "bcrankshaw8@apple.com", "gender": "Female" },
{ "id": 10, "first_name": "Clemens", "last_name": "Ingerfield", "email": "cingerfield9@sciencedaily.com", "gender": "Male" },
{ "id": 11, "first_name": "Raff", "last_name": "Cloney", "email": "rcloneya@wix.com", "gender": "Male" },
{ "id": 12, "first_name": "Patrizio", "last_name": "Kort", "email": "pkortb@loc.gov", "gender": "Male" },
{ "id": 13, "first_name": "Lucho", "last_name": "Faucett", "email": "lfaucettc@w3.org", "gender": "Male" },
{ "id": 14, "first_name": "Brandea", "last_name": "Bohden", "email": "bbohdend@imgur.com", "gender": "Female" },
{ "id": 15, "first_name": "Bernhard", "last_name": "Nisbet", "email": "bnisbete@example.com", "gender": "Male" },
{ "id": 16, "first_name": "Kaine", "last_name": "Antalffy", "email": "kantalffyf@reverbnation.com", "gender": "Male" },
{ "id": 17, "first_name": "Dionysus", "last_name": "Peedell", "email": "dpeedellg@pagesperso-orange.fr", "gender": "Male" },
{ "id": 18, "first_name": "Binnie", "last_name": "Pundy", "email": "bpundyh@hexun.com", "gender": "Female" },
{ "id": 19, "first_name": "Tadd", "last_name": "Blumire", "email": "tblumirei@simplemachines.org", "gender": "Genderfluid" },
{ "id": 20, "first_name": "Anett", "last_name": "Pulham", "email": "apulhamj@berkeley.edu", "gender": "Female" },
{ "id": 21, "first_name": "Elwira", "last_name": "Mugglestone", "email": "emugglestonek@list-manage.com", "gender": "Female" },
{ "id": 22, "first_name": "Shane", "last_name": "Geffcock", "email": "sgeffcockl@domainmarket.com", "gender": "Female" },
{ "id": 23, "first_name": "Millicent", "last_name": "Harome", "email": "mharomem@histats.com", "gender": "Female" },
{ "id": 24, "first_name": "Flo", "last_name": "Wasielewski", "email": "fwasielewskin@cbsnews.com", "gender": "Female" },
{ "id": 25, "first_name": "Leanora", "last_name": "Cloy", "email": "lcloyo@microsoft.com", "gender": "Female" },
{ "id": 26, "first_name": "Tabby", "last_name": "Ahrend", "email": "tahrendp@bluehost.com", "gender": "Female" },
{ "id": 27, "first_name": "Siobhan", "last_name": "Josiah", "email": "sjosiahq@bloglovin.com", "gender": "Female" },
{ "id": 28, "first_name": "Ellette", "last_name": "Posselow", "email": "eposselowr@fda.gov", "gender": "Genderfluid" },
{ "id": 29, "first_name": "Kimberlyn", "last_name": "McCarron", "email": "kmccarrons@gmpg.org", "gender": "Female" },
{ "id": 30, "first_name": "Jacquelin", "last_name": "Adelman", "email": "jadelmant@twitter.com", "gender": "Female" },
{ "id": 31, "first_name": "Sindee", "last_name": "Blanchard", "email": "sblanchardu@dedecms.com", "gender": "Female" },
{ "id": 32, "first_name": "Cully", "last_name": "Jedrzejewsky", "email": "cjedrzejewskyv@smugmug.com", "gender": "Male" },
{ "id": 33, "first_name": "Vinson", "last_name": "MacLardie", "email": "vmaclardiew@shutterfly.com", "gender": "Bigender" },
{ "id": 34, "first_name": "Abbe", "last_name": "Baseke", "email": "abasekex@vimeo.com", "gender": "Male" },
{ "id": 35, "first_name": "Borden", "last_name": "O'Sheeryne", "email": "bosheeryney@globo.com", "gender": "Agender" },
{ "id": 36, "first_name": "Marika", "last_name": "Taft", "email": "mtaftz@toplist.cz", "gender": "Female" },
{ "id": 37, "first_name": "Niel", "last_name": "Skeermer", "email": "nskeermer10@angelfire.com", "gender": "Male" },
{ "id": 38, "first_name": "Abby", "last_name": "McCaskell", "email": "amccaskell11@scientificamerican.com", "gender": "Male" },
{ "id": 39, "first_name": "Row", "last_name": "Feaks", "email": "rfeaks12@netscape.com", "gender": "Female" },
{ "id": 40, "first_name": "Ugo", "last_name": "Hovert", "email": "uhovert13@tamu.edu", "gender": "Male" },
{ "id": 41, "first_name": "Caz", "last_name": "Hayer", "email": "chayer14@mashable.com", "gender": "Male" },
{ "id": 42, "first_name": "Thornton", "last_name": "Hugo", "email": "thugo15@ft.com", "gender": "Male" },
{ "id": 43, "first_name": "Shannah", "last_name": "Giannoni", "email": "sgiannoni16@house.gov", "gender": "Female" },
{ "id": 44, "first_name": "Brenda", "last_name": "Orans", "email": "borans17@friendfeed.com", "gender": "Female" },
{ "id": 45, "first_name": "Ansell", "last_name": "Isaac", "email": "aisaac18@spotify.com", "gender": "Male" },
{ "id": 46, "first_name": "Leese", "last_name": "Cyples", "email": "lcyples19@cdc.gov", "gender": "Female" },
{ "id": 47, "first_name": "Maritsa", "last_name": "Topley", "email": "mtopley1a@4shared.com", "gender": "Female" },
{ "id": 48, "first_name": "Kathryn", "last_name": "Talbot", "email": "ktalbot1b@macromedia.com", "gender": "Female" },
{ "id": 49, "first_name": "Jorgan", "last_name": "Brave", "email": "jbrave1c@who.int", "gender": "Male" },
{ "id": 50, "first_name": "Bartholomeo", "last_name": "Starr", "email": "bstarr1d@google.co.jp", "gender": "Male" },
{ "id": 51, "first_name": "Mei", "last_name": "McKerlie", "email": "mmckerlie1e@samsung.com", "gender": "Female" },
{ "id": 52, "first_name": "Had", "last_name": "Sandercock", "email": "hsandercock1f@salon.com", "gender": "Male" },
{ "id": 53, "first_name": "Calli", "last_name": "Braunle", "email": "cbraunle1g@arizona.edu", "gender": "Female" },
{ "id": 54, "first_name": "Rosalind", "last_name": "Moakes", "email": "rmoakes1h@youtu.be", "gender": "Agender" },
{ "id": 55, "first_name": "Rusty", "last_name": "Tredget", "email": "rtredget1i@usgs.gov", "gender": "Male" },
{ "id": 56, "first_name": "Paola", "last_name": "Constance", "email": "pconstance1j@diigo.com", "gender": "Female" },
{ "id": 57, "first_name": "Christen", "last_name": "Grant", "email": "cgrant1k@over-blog.com", "gender": "Female" },
{ "id": 58, "first_name": "Sukey", "last_name": "Bartholat", "email": "sbartholat1l@hud.gov", "gender": "Non-binary" },
{ "id": 59, "first_name": "Gerianna", "last_name": "Gladhill", "email": "ggladhill1m@parallels.com", "gender": "Female" },
{ "id": 60, "first_name": "Andie", "last_name": "Eddow", "email": "aeddow1n@yelp.com", "gender": "Male" },
{ "id": 61, "first_name": "Avery", "last_name": "Linthead", "email": "alinthead1o@icq.com", "gender": "Male" },
{ "id": 62, "first_name": "Aristotle", "last_name": "McAviy", "email": "amcaviy1p@fastcompany.com", "gender": "Non-binary" },
{ "id": 63, "first_name": "Emlynn", "last_name": "Voelker", "email": "evoelker1q@cpanel.net", "gender": "Female" },
{ "id": 64, "first_name": "Cathryn", "last_name": "Bertomier", "email": "cbertomier1r@simplemachines.org", "gender": "Bigender" },
{ "id": 65, "first_name": "Baxy", "last_name": "Nolli", "email": "bnolli1s@vinaora.com", "gender": "Male" },
{ "id": 66, "first_name": "Adelind", "last_name": "Seater", "email": "aseater1t@blogger.com", "gender": "Female" },
{ "id": 67, "first_name": "Sibylla", "last_name": "McVity", "email": "smcvity1u@dagondesign.com", "gender": "Female" },
{ "id": 68, "first_name": "Base", "last_name": "Klousner", "email": "bklousner1v@utexas.edu", "gender": "Male" },
{ "id": 69, "first_name": "Dorey", "last_name": "Izod", "email": "dizod1w@princeton.edu", "gender": "Female" },
{ "id": 70, "first_name": "Jocko", "last_name": "Siss", "email": "jsiss1x@joomla.org", "gender": "Male" },
{ "id": 71, "first_name": "Karl", "last_name": "Gong", "email": "kgong1y@webnode.com", "gender": "Male" },
{ "id": 72, "first_name": "Pennie", "last_name": "Struther", "email": "pstruther1z@guardian.co.uk", "gender": "Male" },
{ "id": 73, "first_name": "Jaine", "last_name": "Dunbabin", "email": "jdunbabin20@google.cn", "gender": "Female" },
{ "id": 74, "first_name": "Karlyn", "last_name": "Oganesian", "email": "koganesian21@sciencedirect.com", "gender": "Female" },
{ "id": 75, "first_name": "Corby", "last_name": "Vasiljevic", "email": "cvasiljevic22@forbes.com", "gender": "Male" },
{ "id": 76, "first_name": "Jonah", "last_name": "O'Shea", "email": "joshea23@bloglovin.com", "gender": "Male" },
{ "id": 77, "first_name": "Shamus", "last_name": "Fuentes", "email": "sfuentes24@myspace.com", "gender": "Male" },
{ "id": 78, "first_name": "Cord", "last_name": "Lufkin", "email": "clufkin25@g.co", "gender": "Male" },
{ "id": 79, "first_name": "Carola", "last_name": "Meenehan", "email": "cmeenehan26@cbslocal.com", "gender": "Female" },
{ "id": 80, "first_name": "Page", "last_name": "McEttigen", "email": "pmcettigen27@npr.org", "gender": "Female" },
{ "id": 81, "first_name": "Tate", "last_name": "Camelin", "email": "tcamelin28@delicious.com", "gender": "Female" },
{ "id": 82, "first_name": "Tallie", "last_name": "Boswell", "email": "tboswell29@mysql.com", "gender": "Male" },
{ "id": 83, "first_name": "Corrianne", "last_name": "Wrathall", "email": "cwrathall2a@usgs.gov", "gender": "Female" },
{ "id": 84, "first_name": "Kaylee", "last_name": "Groven", "email": "kgroven2b@bandcamp.com", "gender": "Female" },
{ "id": 85, "first_name": "Tomlin", "last_name": "Springle", "email": "tspringle2c@skype.com", "gender": "Male" },
{ "id": 86, "first_name": "Rois", "last_name": "Inggall", "email": "ringgall2d@upenn.edu", "gender": "Genderfluid" },
{ "id": 87, "first_name": "Sydney", "last_name": "Harryman", "email": "sharryman2e@answers.com", "gender": "Male" },
{ "id": 88, "first_name": "Craggy", "last_name": "Cavanaugh", "email": "ccavanaugh2f@themeforest.net", "gender": "Male" },
{ "id": 89, "first_name": "Dareen", "last_name": "Markovich", "email": "dmarkovich2g@histats.com", "gender": "Female" },
{ "id": 90, "first_name": "Dar", "last_name": "Rockall", "email": "drockall2h@ibm.com", "gender": "Male" },
{ "id": 91, "first_name": "Camellia", "last_name": "Zorzenoni", "email": "czorzenoni2i@soup.io", "gender": "Female" },
{ "id": 92, "first_name": "Spenser", "last_name": "Mulvey", "email": "smulvey2j@flickr.com", "gender": "Male" },
{ "id": 93, "first_name": "Harriette", "last_name": "Hurnell", "email": "hhurnell2k@elpais.com", "gender": "Female" },
{ "id": 94, "first_name": "Gay", "last_name": "Rummer", "email": "grummer2l@msu.edu", "gender": "Male" },
{ "id": 95, "first_name": "Shanta", "last_name": "Toupe", "email": "stoupe2m@apache.org", "gender": "Female" },
{ "id": 96, "first_name": "Moses", "last_name": "Burdikin", "email": "mburdikin2n@w3.org", "gender": "Male" },
{ "id": 97, "first_name": "Lyndy", "last_name": "Meach", "email": "lmeach2o@sciencedirect.com", "gender": "Female" },
{ "id": 98, "first_name": "Solomon", "last_name": "Solleme", "email": "ssolleme2p@yellowpages.com", "gender": "Male" },
{ "id": 99, "first_name": "Kasper", "last_name": "Mincher", "email": "kmincher2q@noaa.gov", "gender": "Male" },
{ "id": 100, "first_name": "Coreen", "last_name": "Wornham", "email": "cwornham2r@berkeley.edu", "gender": "Female" }]

function display_data() {
    let row = ""
    for (emp of employees) {
        row = row + `<tr> <td> ${emp.id}</td> 
                     <td> ${emp.first_name}</td> 
                     <td> ${emp.last_name}</td> 
                     <td> ${emp.email}</td> </tr>`
    }
    
    document.getElementById("data").innerHTML = row;
} 